import { $createEmojiNode } from "../nodes/EmojiNode";
import { useEffect } from "react";
import { TextNode } from "lexical";
import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";

import styles from "../../../assets/styles/editor.module.scss";

const emojis = {
  ":grinning:": "😀",
    ":smiley:": "😃",
    ":smile:": "😄",
    ":grin:": "😁",
    ":laughing:": "😆",
    ":satisfied:": "😆",
    ":sweat_smile:": "😅",
    ":rofl:": "🤣",
    ":joy:": "😂",
    ":slightly_smiling_face:": "🙂",
    ":upside_down_face:": "🙃",
    ":wink:": "😉",
    ":blush:": "😊",
    ":innocent:": "😇",
    ":smiling_face_with_three_hearts:": "🥰",
    ":heart_eyes:": "😍",
    ":star_struck:": "🤩",
    ":kissing_heart:": "😘",
    ":kissing:": "😗",
    ":kissing_closed_eyes:": "😚",
    ":kissing_smiling_eyes:": "😙",
    ":smiling_face_with_tear:": "🥲",
    ":yum:": "😋",
    ":stuck_out_tongue:": "😛",
    ":stuck_out_tongue_winking_eye:": "😜",
    ":zany_face:": "🤪",
    ":stuck_out_tongue_closed_eyes:": "😝",
    ":money_mouth_face:": "🤑",
    ":hugs:": "🤗",
    ":hand_over_mouth:": "🤭",
    ":shushing_face:": "🤫",
    ":thinking:": "🤔",
    ":zipper_mouth_face:": "🤐",
    ":raised_eyebrow:": "🤨",
    ":neutral_face:": "😐",
    ":expressionless:": "😑",
    ":no_mouth:": "😶",
    ":smirk:": "😏",
    ":unamused:": "😒",
    ":roll_eyes:": "🙄",
    ":grimacing:": "😬",
    ":face_exhaling:": "😮‍💨",
    ":lying_face:": "🤥",
    ":relieved:": "😌",
    ":pensive:": "😔",
    ":sleepy:": "😪",
    ":drooling_face:": "🤤",
    ":sleeping:": "😴",
    ":mask:": "😷",
    ":face_with_thermometer:": "🤒",
    ":face_with_head_bandage:": "🤕",
    ":nauseated_face:": "🤢",
    ":vomiting_face:": "🤮",
    ":sneezing_face:": "🤧",
    ":hot_face:": "🥵",
    ":cold_face:": "🥶",
    ":woozy_face:": "🥴",
    ":dizzy_face:": "😵",
    ":exploding_head:": "🤯",
    ":cowboy_hat_face:": "🤠",
    ":partying_face:": "🥳",
    ":disguised_face:": "🥸",
    ":sunglasses:": "😎",
    ":nerd_face:": "🤓",
    ":monocle_face:": "🧐",
    ":confused:": "😕",
    ":worried:": "😟",
    ":slightly_frowning_face:": "🙁",
    ":frowning_face:": "☹️",
    ":open_mouth:": "😮",
    ":hushed:": "😯",
    ":astonished:": "😲",
    ":flushed:": "😳",
    ":pleading_face:": "🥺",
    ":frowning:": "😦",
    ":anguished:": "😧",
    ":fearful:": "😨",
    ":cold_sweat:": "😰",
    ":disappointed_relieved:": "😥",
    ":cry:": "😢",
    ":sob:": "😭",
    ":scream:": "😱",
    ":confounded:": "😖",
    ":persevere:": "😣",
    ":disappointed:": "😞",
    ":sweat:": "😓",
    ":weary:": "😩",
    ":tired_face:": "😫",
    ":yawning_face:": "🥱",
    ":triumph:": "😤",
    ":pout:": "😡",
    ":rage:": "😠",
    ":angry:": "😠",
    ":cursing_face:": "🤬",
    ":smiling_imp:": "😈",
    ":imp:": "👿",
    ":skull:": "💀",
    ":skull_and_crossbones:": "☠️",
    ":hankey:": "💩",
    ":poop:": "💩",
    ":shit:": "💩",
    ":clown_face:": "🤡",
    ":japanese_ogre:": "👹",
    ":japanese_goblin:": "👺",
    ":ghost:": "👻",
    ":alien:": "👽",
    ":space_invader:": "👾",
    ":robot:": "🤖",
    ":smiley_cat:": "😺",
    ":smile_cat:": "😸",
    ":joy_cat:": "😹",
    ":heart_eyes_cat:": "😻",
    ":smirk_cat:": "😼",
    ":kissing_cat:": "😽",
    ":scream_cat:": "🙀",
    ":crying_cat_face:": "😿",
    ":pouting_cat:": "😾",
    ":see_no_evil:": "🙈",
    ":hear_no_evil:": "🙉",
    ":speak_no_evil:": "🙊",
    ":kiss:": "💋",
    ":love_letter:": "💌",
    ":cupid:": "💘",
    ":gift_heart:": "💝",
    ":sparkling_heart:": "💖",
    ":heartpulse:": "💗",
    ":heartbeat:": "💓",
    ":revolving_hearts:": "💞",
    ":two_hearts:": "💕",
    ":heart_decoration:": "💟",
    ":heavy_heart_exclamation:": "❣️",
    ":broken_heart:": "💔",
    ":heart:": "❤️",
    ":orange_heart:": "🧡",
    ":yellow_heart:": "💛",
    ":green_heart:": "💚",
    ":blue_heart:": "💙",
    ":purple_heart:": "💜",
    ":brown_heart:": "🤎",
    ":black_heart:": "🖤",
    ":white_heart:": "🤍",
    ":100:": "💯",
    ":anger:": "💢",
    ":boom:": "💥",
    ":collision:": "💥",
    ":dizzy:": "💫",
    ":sweat_drops:": "💦",
    ":dash:": "💨",
    ":hole:": "🕳️",
    ":bomb:": "💣",
    ":speech_balloon:": "💬",
    ":eye_speech_bubble:": "👁️‍🗨️",
    ":left_speech_bubble:": "🗨️",
    ":right_anger_bubble:": "🗯️",
    ":thought_balloon:": "💭",
    ":zzz:": "💤",
    ":wave:": "👋",
    ":raised_back_of_hand:": "🤚",
    ":raised_hand_with_fingers_splayed:": "🖐️",
    ":hand:": "✋",
    ":raised_hand:": "✋",
    ":vulcan_salute:": "🖖",
    ":ok_hand:": "👌",
    ":pinched_fingers:": "🤌",
    ":pinching_hand:": "🤏",
    ":v:": "✌️",
    ":crossed_fingers:": "🤞",
    ":love_you_gesture:": "🤟",
    ":metal:": "🤘",
    ":call_me_hand:": "🤙",
    ":point_left:": "👈",
    ":point_right:": "👉",
    ":point_up_2:": "👆",
    ":fu:": "🖕",
    ":middle_finger:": "🖕",
    ":point_down:": "👇",
    ":point_up:": "☝️",
    ":thumbsup:": "👍",
    ":thumbsdown:": "👎",
    ":fist:": "✊",
    ":fist_raised:": "✊",
    ":facepunch:": "👊",
    ":fist_oncoming:": "👊",
    ":punch:": "👊",
    ":fist_left:": "🤛",
    ":fist_right:": "🤜",
    ":clap:": "👏",
    ":raised_hands:": "🙌",
    ":open_hands:": "👐",
    ":palms_up_together:": "🤲",
    ":handshake:": "🤝",
    ":pray:": "🙏",
    ":writing_hand:": "✍️",
    ":nail_care:": "💅",
    ":selfie:": "🤳",
    ":muscle:": "💪",
};

function emoticonTransform(node) {
  const textContent = node.getTextContent();

  textContent.replace(/:[a-z_]+:/g, (word) => {
    if (word in emojis) {

      const offset = textContent.indexOf(word);
      const length = word.length;

      const textsNodes: TextNode[] = node.splitText(offset, offset + length);

      textsNodes.find((textNode) => {
        if (textNode.getTextContent() === word) {
          textNode.replace($createEmojiNode("emoji", emojis[word]));
        }
      });
    }
  });
}

function useEmojis(editor) {
  useEffect(() => {
    const removeTransform = editor.registerNodeTransform(
      TextNode,
      emoticonTransform,
    );

    return () => {
      removeTransform();
    };
  }, [editor]);
}

export default function EmojisPlugin() {
  const [editor] = useLexicalComposerContext();
  useEmojis(editor);
  return null;
}
